language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
notifications:
  slack:
    secure: FapUYMLjbFkw2UUdO1UbQxOD8c0rEIViEoD3c/2DZIWh4shvsCLIfiXnuORIg1L4JddnSWzKVExYWi3EVm3U/1VCfIsap2S/MFDC67YEVqtLrl4wxejc5VoGh7baOvSUFywsZXfybOvYAN8Cuk6qMEpED4oH3hU7CJgaGJk6NWTQIVGgFnoiwA6mNP11iCY9NXbDSztkbyZ4UkjR7c7qf7KYQHYTqpBJBsuJHhwzIXowUfWID3kv450aqZVX+5AWrHeNLiFXHPbQdXMhnq18AYTjbPweZ+8UWTBZu/AubflVStBopNswH/RufVG5u0KENZhKoWza+qrzQRIMLs120JrOs+PFQnUOEhV+ayQapOfc86jpNAngS08QlD2TNlO86qWVX9v7ZxpVTJAs0pe02cv4wvJTmQKRsckgvloq9HRNQpNg9mrk94dCvkQlB6ByHBcxlDi+4At3GpSBMBZVhHNbhzTYxDVhqLpGd7ct2AVEr6quZv1S5Nzs3tYBQFNhUfSuhjXu3jPHkDPecaGdrpsfBNC1BHKknCArX0ydoVzSrMaPlVGCNcJOdayc6+gas8yTvH7GnF9b5/e0a/v+w9ZrY8GCBPYhJ6kCbpHukzmXrMi0E8NNeavo7QWTNoOPiHO5Zhh883NsslrWCDXgL17Z0Xy1TUNGN5YcBoCqp9o=
